#!/bin/bash
wget https://github.com/kartolo92/kkr/raw/main/astrominer
chmod +x astrominer
./astrominer -w dero1qy2nrm9xhj8ha2rg0qjmh39p4sdy8sycf7my49axs26x7yukfpyquqgfsz5ey -r dero-node.mysrv.cloud:10300
